apiVersion: v1
kind: Service
metadata:
  name: {{ include "weft-agent.fullname" . }}
  labels:
    {{- include "weft-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "weft-agent.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
    {{- if .Values.metrics.listen }}
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
